name: 'Run tests over demo solution'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  demo-test:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: npm install
        with:
          node-version: 18.x
          cache: npm
      - name: tests
        run: npm run testdemo
